# Generated by Django 4.2.1 on 2023-05-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IqueueAP', '0004_remove_shop_number_of_ratings_remove_shop_queue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(default='0000000', editable=False, max_length=100),
        ),
    ]
