# Generated by Django 4.2.1 on 2023-05-11 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IqueueAP', '0006_alter_shop_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_id',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IqueueAP.shop'),
        ),
    ]
