# Generated by Django 4.2.1 on 2023-05-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IqueueAP', '0008_alter_shop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='numb_of_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='queue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
