# Generated by Django 4.2.1 on 2023-05-12 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0011_account_delete_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idc",
                    models.CharField(
                        default="CCCCCCCC",
                        max_length=8,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="shop",
            name="location",
        ),
    ]
