# Generated by Django 4.2.1 on 2023-05-12 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0012_customer_remove_shop_location"),
    ]

    operations = [
        migrations.DeleteModel(
            name="customer",
        ),
        migrations.DeleteModel(
            name="QR",
        ),
        migrations.AlterField(
            model_name="shop",
            name="ids",
            field=models.CharField(
                default="SSSSSSSS",
                max_length=8,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
