# Generated by Django 4.2.1 on 2023-05-13 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0013_delete_customer_delete_qr_alter_shop_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="Coordinates",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="IqueueAP.coordinates",
            ),
        ),
    ]
