# Generated by Django 4.2.1 on 2023-05-18 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0022_account_idc_account_idso_account_lat_account_lon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="idso",
            field=models.CharField(
                default="SSSSSSSS",
                max_length=32,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="idc",
            field=models.CharField(default="CCCCCCCC", max_length=32),
        ),
        migrations.AlterField(
            model_name="account",
            name="idso",
            field=models.CharField(default="OOOOOOOO", max_length=32),
        ),
        migrations.AlterField(
            model_name="shop",
            name="ids",
            field=models.CharField(
                default="SSSSSSSS",
                max_length=32,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
