# Generated by Django 4.2.1 on 2023-06-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0032_alter_review_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="written",
            field=models.BooleanField(default=False),
        ),
    ]
