# Generated by Django 4.2.1 on 2023-06-04 17:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0033_review_written"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="name_of_the_shop",
            field=models.CharField(
                default="SSSSSSSSSSSSSS",
                max_length=36,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="ids",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="IqueueAP.shop"
            ),
        ),
    ]
