# Generated by Django 4.2.1 on 2023-06-04 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0034_review_name_of_the_shop_alter_review_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="name_of_the_shop",
            field=models.CharField(
                default="SSSSSSSSSSSSSSS",
                max_length=36,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
