# Generated by Django 4.2.1 on 2023-06-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0035_alter_review_name_of_the_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop", name="num_reviews", field=models.IntegerField(default=0),
        ),
    ]
