# Generated by Django 4.2.1 on 2023-06-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0037_remove_shop_numb_of_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="queue_no_app",
            field=models.IntegerField(default=0),
        ),
    ]
