# Generated by Django 4.2.1 on 2023-06-07 14:00

import IqueueAP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0038_shop_queue_no_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="img",
            field=models.ImageField(
                default=IqueueAP.models.get_default_image, upload_to="uploads/"
            ),
        ),
    ]
