# Generated by Django 4.2.1 on 2023-06-07 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0042_advertisement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisement",
            name="Shop",
        ),
        migrations.AddField(
            model_name="advertisement",
            name="ids",
            field=models.CharField(
                default="SSSSSSSS",
                max_length=36,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
