# Generated by Django 4.2.1 on 2023-06-10 08:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0043_remove_advertisement_shop_advertisement_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IqueueAP.account",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="Available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="qr",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="slot",
            name="TimeSlot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="IqueueAP.timeslot",
            ),
        ),
        migrations.CreateModel(
            name="WishListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idp", models.CharField(default="SSSSSSSSSS", max_length=100)),
                ("name", models.CharField(default="SSSSSSSSSS", max_length=100)),
                (
                    "wish_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IqueueAP.wishlist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IqueueAP.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchasedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_purchase",
                    models.DateField(default=datetime.date(2023, 6, 10)),
                ),
                ("idp", models.CharField(default="SSSSSSSSSS", max_length=100)),
                ("name", models.CharField(default="SSSSSSSSSS", max_length=100)),
                (
                    "purchase_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IqueueAP.purchaselist",
                    ),
                ),
            ],
        ),
    ]
