# Generated by Django 4.2.1 on 2023-06-14 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0047_rename_shop_review_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseditem",
            name="address",
            field=models.CharField(default="SSSSSSSSSS", max_length=100),
        ),
        migrations.AddField(
            model_name="purchaseditem",
            name="price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="purchaseditem",
            name="shop",
            field=models.CharField(default="SSSSSSSSSS", max_length=100),
        ),
        migrations.AlterField(
            model_name="purchaseditem",
            name="date_of_purchase",
            field=models.DateField(default=datetime.date(2023, 6, 14)),
        ),
    ]
