# Generated by Django 4.2.1 on 2023-05-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coordinates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.IntegerField()),
                ("longitude", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="QR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("QRid", models.CharField(max_length=50)),
                ("ids", models.CharField(max_length=50)),
                ("idso", models.CharField(max_length=50)),
                ("idc", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                ("available", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("max_numb_clients", models.IntegerField()),
                ("id_shop", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                ("queue", models.IntegerField()),
                ("rating", models.FloatField()),
                ("number_of_ratings", models.IntegerField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IqueueAP.coordinates",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("shop_discount", models.FloatField()),
                ("id_product", models.CharField(max_length=50)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="IqueueAP.shop"
                    ),
                ),
            ],
        ),
    ]
