# Generated by Django 4.2.1 on 2023-05-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IqueueAP', '0002_coordinates_qr_timeslot_shop_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
