# Generated by Django 4.2.1 on 2023-05-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IqueueAP', '0005_shop_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(default='0000000', max_length=100),
        ),
    ]
