# Generated by Django 4.2.1 on 2023-05-11 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0009_shop_numb_of_ratings_shop_queue_shop_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=150)),
                ("birthday", models.DateField()),
                (
                    "idc",
                    models.CharField(
                        default="BBBBBBBB",
                        max_length=8,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Account",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="id_shop",
        ),
        migrations.AddField(
            model_name="shop",
            name="ids",
            field=models.CharField(
                default="AAAAAAAA",
                max_length=8,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
        migrations.AlterField(
            model_name="coordinates",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="coordinates",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="id_product",
            field=models.CharField(
                max_length=8, validators=[django.core.validators.MinLengthValidator(8)]
            ),
        ),
    ]
