# Generated by Django 4.2.1 on 2023-05-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "IqueueAP",
            "0010_customer_delete_account_remove_shop_id_shop_shop_ids_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=150)),
                ("birthday", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
