# Generated by Django 4.2.1 on 2023-05-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0014_shop_coordinates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="Coordinates",
        ),
        migrations.AddField(
            model_name="shop",
            name="lat",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="shop",
            name="lon",
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name="Coordinates",
        ),
    ]
