# Generated by Django 4.2.1 on 2023-05-18 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0021_rename_shop_name_booking_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="idc",
            field=models.CharField(
                default="CCCCCCCC",
                max_length=8,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="idso",
            field=models.CharField(
                default="OOOOOOOO",
                max_length=8,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="lat",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="lon",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="reward",
            field=models.IntegerField(default=0),
        ),
    ]
