# Generated by Django 4.2.1 on 2023-05-21 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0023_shop_idso_alter_account_idc_alter_account_idso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id_product",
            field=models.CharField(
                max_length=36, validators=[django.core.validators.MinLengthValidator(8)]
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="ids",
            field=models.CharField(
                default="SSSSSSSS",
                max_length=36,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="idso",
            field=models.CharField(
                default="SSSSSSSS",
                max_length=36,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
