# Generated by Django 4.2.1 on 2023-05-25 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IqueueAP', '0024_alter_product_id_product_alter_shop_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.AddField(
            model_name='product',
            name='idp',
            field=models.CharField(default='SSSSSSSS', max_length=36, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AddField(
            model_name='product',
            name='ids',
            field=models.CharField(default='SSSSSSSS', max_length=36, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AddField(
            model_name='product',
            name='idso',
            field=models.CharField(default='SSSSSSSS', max_length=36, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
