# Generated by Django 4.2.1 on 2023-06-01 07:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0025_remove_product_id_product_remove_product_shop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="idp",
            field=models.CharField(
                default="PPPPPPPP",
                max_length=36,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="idso",
            field=models.CharField(
                default="OOOOOOOO",
                max_length=36,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("available", models.BooleanField(default=True)),
                (
                    "idc",
                    models.CharField(
                        max_length=36,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "TimeSlot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IqueueAP.timeslot",
                    ),
                ),
            ],
        ),
    ]
