# Generated by Django 4.2.1 on 2023-06-02 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0026_alter_product_idp_alter_product_idso_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to=None)),
                (
                    "idc",
                    models.CharField(
                        max_length=36,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "idso",
                    models.CharField(
                        default="OOOOOOOO",
                        max_length=36,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "ids",
                    models.CharField(
                        default="SSSSSSSS",
                        max_length=36,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "idQR",
                    models.CharField(
                        default="QQQQQQQQ",
                        max_length=36,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                ("number", models.IntegerField(default=-1)),
                ("time", models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="slot",
            name="number",
            field=models.IntegerField(default=1),
        ),
    ]
