# Generated by Django 4.2.1 on 2023-06-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0027_qr_alter_slot_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
        migrations.AlterField(
            model_name="qr",
            name="img",
            field=models.TextField(),
        ),
    ]
