# Generated by Django 4.2.1 on 2023-06-02 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0028_delete_booking_alter_qr_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="qr",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
