# Generated by Django 4.2.1 on 2023-06-02 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0029_qr_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qr",
            name="time",
        ),
        migrations.AddField(
            model_name="qr",
            name="time_end",
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name="qr",
            name="time_start",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
