# Generated by Django 4.2.1 on 2023-06-04 14:15

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0030_remove_qr_time_qr_time_end_qr_time_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="qr", name="scanned", field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "idc",
                    models.CharField(
                        max_length=36,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "ids",
                    models.ForeignKey(
                        default="0",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IqueueAP.shop",
                    ),
                ),
            ],
        ),
    ]
