# Generated by Django 4.2.1 on 2023-06-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0031_qr_scanned_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review", name="review", field=models.TextField(default=""),
        ),
    ]
