# Generated by Django 4.2.1 on 2023-06-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0036_shop_num_reviews"),
    ]

    operations = [
        migrations.RemoveField(model_name="shop", name="numb_of_ratings",),
    ]
