# Generated by Django 4.2.1 on 2023-06-07 15:08

import IqueueAP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0040_alter_shop_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="img",
            field=models.ImageField(
                default=IqueueAP.models.get_default_image,
                max_length=10000,
                upload_to="images/",
            ),
        ),
    ]
