# Generated by Django 4.2.1 on 2023-06-07 15:22

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0041_alter_shop_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField(default=datetime.date.today)),
                ("date_end", models.DateField(default=datetime.date.today)),
                (
                    "ADVid",
                    models.CharField(
                        default="AAAAAAAA",
                        max_length=36,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "Shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IqueueAP.shop",
                    ),
                ),
            ],
        ),
    ]
