# Generated by Django 4.2.1 on 2023-06-11 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0044_wishlist_product_available_product_qr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="lon",
        ),
        migrations.AlterField(
            model_name="purchaseditem",
            name="date_of_purchase",
            field=models.DateField(default=datetime.date(2023, 6, 11)),
        ),
    ]
