# Generated by Django 4.2.1 on 2023-06-13 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0045_remove_shop_lat_remove_shop_lon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="ids",
            new_name="shop",
        ),
        migrations.AlterField(
            model_name="purchaseditem",
            name="date_of_purchase",
            field=models.DateField(default=datetime.date(2023, 6, 13)),
        ),
    ]
