# Generated by Django 4.2.1 on 2023-06-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IqueueAP", "0046_rename_ids_review_shop_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="shop",
            new_name="ids",
        ),
    ]
